### PR TITLE
reviewed list of gradle books - proposal for books.md 

### PR DESCRIPTION
**Pull request by ivonasto**
Books metadata file with existing titles in English from the 2020 list in issue #98. 

Images to be added.

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Thanks for the patch @ivonasto! We can merge the first version without the images, but we will still need `books.html` to be added to the page. Also, please add the page to the navigation under the Resources section

**Comment by oleg-nenashev** [comment]
Hi @ivonasto , do you plan to finish this PR? Or is any help needed?

**Comment by ivonasto** [comment]
Hi, @oleg-nenashev. Yes, I will finish it. I have trouble with the dev container, almost got it working. I have more time now to look into it. Thank you

**Comment by oleg-nenashev** [comment]
Sure. If you need any help with sorting the issue, just ask on the #docs or #contributing Slack channels

**Comment by ivonasto** [comment]
Hello, I did the preliminary version. If you have any visual or code suggestions, please let me know.

Could you upload the book covers so I can replace the placeholder image?

**Comment by oleg-nenashev** [comment]
Since it is deployed from the `main` branch, good opportunity to do a preview implementation :)

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Thank you @ivonasto ! Just a few items before we can merge

* Could you please add authors to the metadata and visualization? Just a name would be good enough, Author+URL would be better
* The cover images will need some approvals. I suggest putting a default image for now, see below

Book_Cover

**Review by oleg-nenashev — APPROVED** [review]
it looks good to me as an initial implementation, thank you! I will probably polish it a bit later so that there is no need to do HTML injection

**Pull request merged**
