### PR TITLE
Fix - SEO metadata for GSoC pages.

### PR DESCRIPTION
**Pull request by Tanish-Ranjan**
This PR adds SEO metadata such as title and description to all the GSoC pages.
Fix for issue: https://github.com/gradle/community/issues/100

### CODE REVIEW

**Comment by Tanish-Ranjan** [comment]
@oleg-nenashev Could you suggest the description for Sidhaarth's GSoC page? I am not quite aware of the scope of his project.

https://github.com/gradle/community/pull/105/files#diff-7f58435e33957cddde0dd6629e988394913abd4efbb9be187bed1be9d16b0999R4

**Comment by Tanish-Ranjan** [comment]
Should we remove these? https://github.com/gradle/community/pull/105/files#diff-7f58435e33957cddde0dd6629e988394913abd4efbb9be187bed1be9d16b0999R63-R64

**Comment by Tanish-Ranjan** [comment]
The three project pages for GSoC 2024:
1. https://community.gradle.org/events/gsoc/2024/gradle-build-server-android/
2. https://community.gradle.org/events/gsoc/2024/gradle-build-server-devx/
3. https://community.gradle.org/events/gsoc/2024/checkstyle-plugin/

they all follow slightly different format. Should we leave it as is or should they be made consistent?

**Comment by oleg-nenashev** [comment]
> @oleg-nenashev Could you suggest the description for Sidhaarth's GSoC page? I am not quite aware of the scope of his project.

"The goal of this project is to leverage the Build Server Protocol implementation by the Gradle Build Server in Eclipse IDE (via the Eclipse Buildship plugins)" or so

> Should we remove these?

Yup, or replace by actual links

> they all follow slightly different format. Should we leave it as is or should they be made consistent?

I recommend leaving it as is

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the patches and for the GSoC status updates!

**Pull request merged**
